version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    restart: always
    environment:
      REDIS_PASSWORD: 123
      REDIS_DB: 0





  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    restart: always
